version: '3.6'

services:
  postgres_restaurant_ft:
    container_name: restaurant_ft_postgres_container
    image: postgres:12.3
    environment:
      POSTGRES_DB: ${RESTAURANT_FT_RDS_DB_NAME:-restaurant_ft}
      POSTGRES_USER: ${RESTAURANT_FT_RDS_USERNAME:-restaurant_ft}
      POSTGRES_PASSWORD: ${RESTAURANT_FT_RDS_PASSWORD:-testpwd1}
      PGDATA: /data/postgres_restaurant_ft
    volumes:
      - postgres_restaurant_ft:/data/postgres_restaurant_ft
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_restaurant_ft:
